Drop_Shot/urls.py
from django.conf.urls import url, include
from django.contrib import admin


urlpatterns = [
    url(r'^message/', include('message.urls', namespace='message')),
    url(r'^admin/', admin.site.urls),
]

message/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^add/$', views.add, name='add'),
    url(r'^delete/$', views.delete, name='delete'),
    url(r'^edit/(?P<editing_id>\d+)/$', views.edit, name='edit'),
    url(r'^dropshot/$', views.dropshot, name='dropshot'),
    url(r'^addall/$', views.add_all, name='addall'),
    url(r'^view/(?P<member_id>\d+)/$', views.get_message, name='get_message'),
    url(r'^top/$', views.top, name='top'),
    url(r'^top2/$', views.top2, name='top2'),
    url(r'^bomb_room/$', views.bomb_room, name='bomb_room'),
    url(r'^bomb/$', views.bomb, name='bomb'),
]

message/models.py
from django.db import models


class Member(models.Model):
    year = models.CharField(max_length=20)
    name = models.CharField(max_length=20, unique=True)

    def __str__(self):
        return (u'{0}:{1}...'.format
                (self.id, self.year, self.name))

    class Meta:
        db_table = "message_member"


class Message(models.Model):
    create_for = models.ForeignKey(
        "Member", to_field='name', related_name='create_for')
    message = models.CharField(max_length=255)
    author = models.ForeignKey(
        "Member", to_field='name', related_name='author')

    def __str__(self):
        return (u'{0}:{1}...'.format
                (self.id, self.message[:10], self.create_for, self.author, ))

    class Meta:
        db_table = "message_message"

message/forms.py
from django import forms
from . import models
from .get_member import GetMember


class MessageForm(forms.Form):
    message = forms.CharField(
        label='メッセージ',
        max_length=255,
        required=None,
        widget=forms.Textarea(),
    )
    author = forms.ModelChoiceField(
        models.Member.objects.values_list('name', flat=True),
        empty_label='------',
        label='投稿者',
        required=True,
        to_field_name="name",
    )
    create_for = forms.ModelChoiceField(
        models.Member.objects.values_list('name', flat=True),
        empty_label='------',
        label='相手',
        required=True,
        to_field_name="name",
    )


class MemberForm(forms.Form):
    YEAR_CHOICES = GetMember.year_choices
    NAME_CHOICES = GetMember.name_choices
    year = forms.CharField(
        label='学年',
        required=True,
        widget=forms.Select(choices=YEAR_CHOICES)
    )
    name = forms.CharField(
        label='名前',
        max_length=20,
        required=True,
        widget=forms.Select(choices=NAME_CHOICES)
    )


class SendForm(forms.Form):
    YEAR_CHOICES = GetMember.year_choices
    NAME_CHOICES = GetMember.name_choices
    message = forms.CharField(
        label='メッセージ',
        max_length=255,
        required=None,
        widget=forms.Textarea(),
    )
    create_for = forms.ModelChoiceField(
        models.Member.objects.values_list('name', flat=True),
        empty_label='------',
        label='相手',
        required=True,
        to_field_name="name",
    )

message/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST
from .models import Message
from .models import Member
from .forms import MessageForm, SendForm
from .get_member import GetMember
import random


def index(request):
    d = {
        "messages": Message.objects.all(),
        "members": Member.objects.all(),
    }
    return render(request, "index.html", d)


def add(request):
    form = MessageForm(request.POST or None)
    if form.is_valid():
        author = Member.objects.get(name=form.cleaned_data['author'])
        create_for = (
            Member.objects.get(name=form.cleaned_data['create_for']))
        Message.objects.create(
            message=form.cleaned_data['message'],
            author=author,
            create_for=create_for,
        )
        # **:可変長引数 / form.cleaned_data: バリデーションを通過したデータが入ってる
        """今回のデータはMessageeクラスで定義されたmessageとcreated_at
            class Message(models.Model):
            message = models.CharField(max_length=255)
            created_at = models.DateTimeField(auto_now_add=True)"""
        return redirect('message:index')
    d = {
        'message_form': form,
    }
    return render(request, 'edit.html', d)


def edit(request, editing_id):
    message = get_object_or_404(Message, id=editing_id)
    if request.method == 'POST':
        message_form = MessageForm(request.POST)
        if message.is_valid():
            author = Member.objects.get(name=message.cleaned_data['author'])
            create_for = (
                Member.objects.get(name=message.cleaned_data['create_for']))
            Message.objects.create(
                message=message.cleaned_data['message'],
                author=author,
                create_for=create_for,
            )
            return redirect('message:index')
    else:
        # GETリクエスト（初期表示）時はDBに保存されているデータをFormに結びつける
        message_form = MessageForm(
            {'message': message.message,
             'author': message.author.name,
             'create_for': message.create_for.name,
             })
    d = {
        'message_form': message_form,
    }

    return render(request, 'edit.html', d)


@require_POST
def delete(request):
    delete_ids = request.POST.getlist('delete_ids')
    if delete_ids:
        Message.objects.filter(id__in=delete_ids).delete()
    return redirect('message:index')


def dropshot(request):
    d = {
        'messages': Message.objects.all(),
        'members': Member.objects.all(),
    }
    return render(request, 'dropshot.html', d)


def add_all(request):
    def save(year, name):
        data = Member(name=name, year=year)
        data.save()
        return()
    for member in GetMember.members:
        name = member[1]
        year = member[0]
        save(year, name)
    return redirect('message:index')


def get_message(request, member_id):
    master = Member.objects.get(id=member_id)
    name = master.name
    messages = Message.objects.filter(create_for=name)
    form = SendForm(request.POST or None)
    if form.is_valid():
        create_for = (
            Member.objects.get(name=form.cleaned_data['create_for']))
        Message.objects.create(
            message=form.cleaned_data['message'],
            author=master,
            create_for=create_for,
        )
        return redirect('message:get_message', member_id)
    d = {
        'messages': messages,
        'name': name,
        'send_form': form,
    }
    return render(request, 'member_page.html', d)


def top(request):
    return render(request, 'top.html')


def top2(request):
    return render(request, 'top2.html')


def bomb_room(request):
    return render(request, 'bomb_room.html')


def bomb(request):
    def delete_all():
        h = Message.objects.all()
        h.delete()
        return
    dice = random.randint(0, 99)
    if dice < 5:
        delete_all()
        d = {'result': u'メッセージを削除しました',
             'q': False}
    else:
        d = {'result': u'不発',
             'q': True}
    return render(request, 'bomb.html', d)

templates/base.html
<!DOCTYPE html>
{% load static %}
{% load bootstrap3 %}
<html>
<head lang="ja">
  <meta charset="utf-8">
  <link rel="stylesheet" type='text/css' href="{% static 'css/bootstrap.css' %}" />
</head>
<body>

<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'message:top' %}">Dropshot</a>
    </div>
    <div class="navbar-collapse collapse" id="myNavbar">
      <ul class="nav navbar-nav">
        <li><a class="active" href="{% url 'message:dropshot' %}">メンバー</a></li>
        <li><a href="{% url 'message:add' %}">メッセージを送る</a></li>
        <li><a href="{% url 'message:index' %}">メッセージ一覧</a></li>
        <li><a href="{% url 'message:bomb_room' %}">自爆スイッチへ</a></li>
      </ul>
    </div>
  </div>
</nav>
{% block body %}
{% endblock %}
</body>
</html>

templates/bomb.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8"><h2>{{ result }}</h2></div>
  </div>
  {% if q %}
  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <p><h2>コンティニュー？</h2></p>
      <ul>
        <li><a href="{% url 'message:bomb_room' %}"><h3>YES</h3></a></li>
        <li><a href="{% url 'message:bomb_room' %}"><h3>はい</h3></a></li>
      </ul>
    </div>
  </div>
  {% endif %}
</div>

{% endblock %}

templates/bomb_room.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8"><h1><font size="7" color="#ff0000">WARNING</font></h1></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6">
      <h2><b>自爆スイッチ</b></h2>
      <p>
        <h3><b>絶対に押さないで下さい</b></h3><br>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8 text-center">
      <a href="{% url 'message:bomb' %}"><img src="{% static 'img/icon1.png' %}" alt="自爆スイッチ" width="40%" height="40%"></a>
    </div>
  </div>
</div>

{% endblock %}

templates/dropshot.html
{% extends "base.html" %}

{% block body %}

<div class="container-fluid">
  <div class="row">
    <div class="col-md-3"><h1>Drop Shot</h1></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-4">
      <table class="table table-striped" style="table-layout:fixed;">
        <thead>
          <tr>
            <th class="text-center"><h3>学年</h3></th>
            <th  class="text-center"><h3>名前</h3></th>
          </tr>
        </thead>
        <tbody>
          {% for member in members %}
            <tr>
              <td class="text-center"><h4>{{ member.year }}</h4></td>
              <td class="text-center"><a href="{% url 'message:get_message' member.id %}"><h4>{{ member.name }}</h4></a></td>
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>

</div>
{% endblock %}

templates/edit.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}
<form action="" method="post">
  <div class="container-fluid">
    <div class="row"><div class="col-sm-2"><h3 class="text-primary">入力画面</h3></div></div>
    <div class="row">
      <div class="col-sm-4">
        {% bootstrap_label message_form.author.label %}:
        {% csrf_token %}
        {% bootstrap_field message_form.author layout='horizontal' show_label=False %}
      </div>
    </div>
    <div class="row">
          <div class="col-sm-4">
            {% bootstrap_label message_form.create_for.label %}:
            {% csrf_token %}
            {% bootstrap_field message_form.create_for layout='horizontal' show_label=False %}
          </div>
    </div>
    <div class="row">
      <div class="col-sm-8">
        {% bootstrap_label message_form.message.label %}
        {% csrf_token %}
        {% bootstrap_field message_form.message layout='horizontal' show_label=False %}
      </div>
    </div>
    <div class="row" style="margin: 5px;">
      <input type="submit" class="btn btn-success" value="登録">
      <a href="{% url 'message:index' %}" style="text-center">一覧へ</a>
    </div>
  </div>
</form>

{% endblock %}

templates/index.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}
<form action="{% url 'message:delete' %}" method="post">


<div class="container">
  <div class="row">
    <div class="col-md-3"><h2 class="text-info">{{ name }}</h2></div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-1">
      <h3 class="text-info">Message</h3>
    </div>
  </div>
  {% for message in messages %}
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-1">
      <dl class="well">
        <dt>
          <h4 class='text-success'><input type="checkbox" name="delete_ids" value="{{ message.id }}">
            <small class="text-muted">to&emsp;</small>{{ message.create_for.name }}&emsp;<small class="text-muted">from&emsp;{{ message.author.name }}</small>
          </h4>
        </dt>
        <dd>{{ message.message }}</dd>
      </dl>
    </div>
  </div>
  {% endfor %}
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-1">
      {% csrf_token %}
      <a href="{% url 'message:add' %}" class="btn btn-info">add</a>
      <input type="submit" class="btn btn-danger" value="Delete">
      <!--input type="submit" class="btn" value="AddAll"-->
    </div>
  </div>

</form>
{% endblock %}

templates/member_page.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

<div class="container">
  <div class="row">
    <div class="col-md-3"><h2 class="text-info">{{ name }}</h2></div>
  </div>
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <h3 class="text-info">Message</h3>
    </div>
  </div>
  {% for message in messages %}
  <div class="row">
    <div class="col-md-6 col-md-offset-1">
      <dl class="well">
        <dt>
          <h4 class='text-success'><small class="text-muted">from&emsp;</small>{{ message.author.name }}</h4>
        </dt>
        <dd>{{ message.message }}</dd>
      </dl>
    </div>
  </div>
  {% endfor %}
  <hr>
  <form action="" method="post">
    <div class="row">
      <div class="col-md-6 col-md-offset-1">
        <h3 class="text-info">Send Message</h3>
      </div>
    </div>
    <div class="row">
          <div class="col-md-5 col-md-offset-1">
            相手:
            {% csrf_token %}
            {% bootstrap_field send_form.create_for layout='horizontal' show_label=False %}
          </div>
    </div>
    <div class="row">
      <div class="col-md-8 col-md-offset-1">
        メッセージ:
        {% csrf_token %}
        {% bootstrap_field send_form.message layout='horizontal' show_label=False %}
      </div>
    </div>
    <div class="row" style="margin: 5px;">
      <div class="col-md-1 col-md-offset-1">
        <input type="submit" class="btn btn-success" value="Send">
      </div>
    </div>
  </form>
</div>
{% endblock %}

templates/top.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block body %}

<div class="container-fluid jumbotron">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <h1 class="text-center">Drop Shot</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <h3 class="text-right">深井椋太</h3>
    </div>
  </div>
    <div class="row">
      <div class="col-xs-12 col-md-offset-2 col-md-8">
        <p>おはようございます。大学院修士一年の深井と申します。</p>
        <p>ここ数年小説を投稿していたのですが、日本語を書くのに飽きました。
           かといって<a href="https://www.ets.org/jp/toefl">英語を書くのは面倒くさい</a>し、第三言語なんて勉強してこともないので、機械語で書くこととしました。</p>
        <p>使用した言語は<a href="https://www.python.org">Python3.5</a>とHTML5です。CSSは<a href="http://getbootstrap.com">Bootstrap氏</a>に任せております。ご了承下さい。</p>
        <p>ついでにプログラミングは独学なので、至らないところもあるかと存じますが、何か気づいた点などがございましたら気兼ねなくご指摘いただけると幸いです。</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-offset-2 col-md-8">
        <h2>自己紹介</h2>
        <p>自己紹介といっても、名前はもう表明してあるので、とくに改めて紹介することはないかと。</p>
        <p>強いて言うなら趣味がたくさんあります。というのも趣味が増やすのが趣味みたいなところがあるので仕方ないですね。</p>
        <p>すでに何が趣味で、何が暇つぶしなのかわからなくなっていますが、せっかくなので列挙してみます。</p>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-offset-2 col-md-8">
        <h4><dl>
          <dt>読書</dt>
          <dd>SFが好きです。特に<a href="https://www.amazon.co.jp/攻殻機動隊-1-KCデラックス-士郎-正宗/dp/406313248X">サイバーパンク</a>とハードSF。好きな作家は<a href="https://www.amazon.co.jp/Self-Reference-ENGINE-ハヤカワ文庫JA-円城-塔/dp/415030985X/ref=sr_1_1?ie=UTF8&qid=1485416524&sr=8-1&keywords=self+reference+engine">円城塔</a></dd>
          <dt>格ゲー</dt>
          <dd>ウル４:コーディーとヴァイパー、アルカプ:マグニ,アイアン,ストレンジ、BB:レイチェル、ペルソナ:直人、GG:テスタ、他。設置キャラが好きです。</dd>
          <dt>音楽</dt>
          <dd>サンホラ、北欧メタル</dd>
          <dt>TCG</dt>
          <dd>最近ほそぼそとギャザやってます。白が好き。シャドバ:コントロールビショップ、ハースストーン:コントロールプリ</dd>
          <dt>パチスロ</dt>
          <dd>最近あんま行ってない。HANABI一択。現状プラスマイナス０</dd>
          <dt>TRPG</dt>
          <dd>一緒に出来るヒト探してます。経験:CoC,ウタカゼ</dd>
          <dt>旅行</dt>
          <dd>いつでも行きたい。電車は嫌い。アメリカに行きたい。</dd>
          <dt>食べること</dt>
          <dd>孤独のグルメごっこ</dd>
          <dt>将棋</dt>
          <dd>居飛車党、対振りは相手が熊んなければ急戦、熊ったらいび穴。相居飛車は矢倉にならないように角換わりか、横歩に誘導してます。</dd>
          <dt>プログラミング</dt>
          <dd>一番使えるのはpython。一応javascriptも読める。HTMLは嗜み。</dd>
          <dt>小説を書く</dt>
          <dd>あんま書いてない。今年のDropShotは夏目漱石とリレー小説を企画していたが断念。こんな感じになった。</dd>
          <dt>万年筆のインク</dt>
          <dd>きれいですよね。</dd>
        </dl></h4>
      </div>
    </div>
    <div class="row">
      <div class="col-xs-12 col-md-offset-2 col-md-8">
        <p>軽く思いついただけでこんな感じです。ハマるととことんハマって半年くらいで飽きる周期を繰り返してます。格ゲーあたりはそこら辺の人には負けないと思います。</p>
        <p>趣味の話になったらなんでもついていける自信はあるので、なにか面白い趣味をもってるひとは教えてください。芸術系以外は興味津々です。</p>
      </div>
    </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8 text-center">
      <nav aria-label="Page navigation">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="#">Previous</a></li>
          <li class="page-item"><a class="page-link" href="#">1</a></li>
          <li class="page-item"><a class="page-link" href="{% url 'message:top2' %}">2</a></li>
          <li class="page-item"><a class="page-link" href="{% url 'message:top2' %}">Next</a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>


{% endblock %}

templates/top2.html
{% extends "base.html" %}
{% load bootstrap3 %}
{% load static %}

{% block body %}

<div class="container-fluid jumbotron">
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <h1 class="text-center">Drop Shot</h1>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
      <h4>つづき..</h4>
    </div>
  </div>
  <div class="row">
    <div class="col-xs-12 col-md-offset-2 col-md-8">
    <font size="4">
      <br>
      <p>dropshotといえばなんかみんなに一言メッセージみたいなのやってるひと多いですよね。ってことで<a href="{% url 'message:dropshot' %}"></a>実装しました。</p>
      <p>あれって色んな人がやってるんですが、誰が誰にどんなメッセージを送ってるのかわかりにくいので、わかりやすくしようと思いました。</p>
      <p>上のメンバーってところを押すと飛べます。各位自分の名前を押してもらえれば自分へのメーッセージが見れますし、誰かにメッセージを送ることもできます。</p>
      <p>さらに皆さんの名前が予め登録されていますね。これ、テニス部のホームページから引っ張ってきていますので、ホームページが滞りなく更新されれば、
        常にメンバーが最新の状態に保たれます。まあ新１年生が入るころには、このサイトは潰していると思いますが。</p>
      <p>さて、ここで一つ先輩として苦言を呈したいと思います。まずこれを見て下さい。</p>
      <p><img src="{% static 'img/img1.jpg' %}" alt="Figure 1" width="100%" height="100%"></p>
      <p><a href="http://ustt-2011.com/buinnshoukai.html">テニス部ホームページの部員紹介</a>のソースですね。</p>
      <p>いくらもっちーのことを愛していても、一人のスタイルだけいじりすぎやしませんか？これのせいでもっちー以下の名前の取得に手こずりました。
        そしてこの長いスタイル宣言の結果がこれです。</p>
      <p><img src="{% static 'img/img2.jpg' %}" alt="Figure 2"></p>
      <p>やるならもっと派手にやりませんか？まあとりあえずホームページ係の方、コードはきれいにしておくことをおすすめしておきます。</p>
      <p>文章の方は以上です。他のところは練習がてら作ったもので、webページもテスト用なので実用性はないです。使ってもいいですがこちらの都合でそのうち勝手に消します。</p>
      <p>とは言っても皆さんにメッセージを書いたので見たいヒトは自分の名前を押すか、メッセージ一覧からどうぞ</p>
      <p>面白いので自爆ボタンも設置しました。押すと確率５％で発動して、全メッセージが消去されます。これ、押したくなりませんか？僕なら押します。</p>
    </font>
    </div>
  </div>
</div>
<div class="container-fluid">
  <div class="row">
    <div class="col-xs-12 col-md-offset-3 col-md-6 text-center">
      <nav aria-label="Page navigation">
        <ul class="pagination">
          <li class="page-item"><a class="page-link" href="{% url 'message:top' %}">Previous</a></li>
          <li class="page-item"><a class="page-link" href="{% url 'message:top' %}">1</a></li>
          <li class="page-item"><a class="page-link" href="{% url 'message:top2' %}">2</a></li>
          <li class="page-item"><a class="page-link" href="{% url 'message:top2' %}">Next</a></li>
        </ul>
      </nav>
    </div>
  </div>
</div>

{% endblock %}